name: Build for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build release executable
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: wechat-backup-windows
        path: target/release/wechat-backup.exe